spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://115.29.238.203:30001/diancan?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  type-aliases-package: com.guang.bishe.mapper
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
server:
  port: 82